/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern JLCX86Generator. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "JLCX86Generator.H"
#include "util.h"
#include "Printer.H"

#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <cstdlib>

#include "llvm/Support/raw_ostream.h"

static PrintAbsyn p = PrintAbsyn();

static const std::string GeneratorName = "JLCX86Generator";
std::ofstream outfile("x86output.s");

#define ERRPR_HANDLE(msg) \
  while(1){ \
  std::cerr << "Error: " << msg << std::endl; \
  LLVM_module_->print(llvm::outs(), nullptr); \
  exit(1);\
  }

/*
  this function is used to convert the type_enum to string
  @return: llvm::Type*
  @param: type_enum t
*/
llvm::Type* JLCX86Generator::convertType(type_enum t){
  switch (t)
  {
  case INT:
    return llvm::Type::getInt32Ty(*LLVM_Context_);
  case DOUB:
    return llvm::Type::getDoubleTy(*LLVM_Context_);
  case BOOL:
    return llvm::Type::getInt1Ty(*LLVM_Context_);
  case VOID:
    return llvm::Type::getVoidTy(*LLVM_Context_);
  case CHAR:
    return llvm::Type::getInt8Ty(*LLVM_Context_);
  case STRING: // the atcually out is ptr not i8*, is it ok? @todo
    return llvm::Type::getInt8PtrTy(*LLVM_Context_);
  default:
    std::cerr << "Error, Unknown type:" << to_string(t) << std::endl;
    exit(1);
  }
}

void JLCX86Generator::addExternalFunc(){
  for (auto & func : globalContext.funcs)
  {
    addFuncDeclearation(func.second);
  }  
}

void JLCX86Generator::addFuncDeclearation(Frame &frame){
  // see the tutorial about llvm: 
  std::string func_name = frame.name;
  auto llvm_return_type = convertType(frame.returnType);
  std::vector<llvm::Type*> llvm_args;
  for (auto & arg : frame.args)
  {
    llvm_args.push_back(convertType(arg.second));
  }
  llvm::FunctionType* func_type = 
    llvm::FunctionType::get(llvm_return_type, llvm_args, false);
  auto func_dec = llvm::Function::Create(
      func_type, 
      llvm::Function::ExternalLinkage, 
      func_name, 
      LLVM_module_.get());
  
  std::string ss;
  llvm::raw_string_ostream ss2(ss);
  func_dec->print(ss2);
  DEBUG_PRINT("Add function declearation: " + ss);
}



void JLCX86Generator::visitProgram(Program *program)
{
  /* Code For Program Goes Here */
  /* iterate through the top definitions */
  // this part is same as the type checker, will add all the functions to the context
  restoreFunctionArgQueue();
  outfile << "section .data" << std::endl;
  outfile << "section .text" << std::endl;
  outfile << "global _start" << std::endl;
  for (ListTopDef::iterator top_def = program->listtopdef_->begin() ; top_def != program->listtopdef_->end() ; ++top_def)
  {
    FnDef* fn_def = reinterpret_cast<FnDef*>(*top_def);
    visitIdent(fn_def->ident_);
    // add the function to the global context
    globalContext.addFrame(fn_def->ident_);
    globalContext.currentFrameName = fn_def->ident_;

    // update the function return type
    Frame& func = globalContext.getFrame(fn_def->ident_);
    fn_def->type_->accept(this);
    func.returnType = temp_type;

    // check function arguments
    if (fn_def->listarg_) fn_def->listarg_->accept(this);

    // add to llvm module - start
    // @todo maybe we can drop the self-defined CONTEXT, 
    // and use the llvm::Module directly

    auto llvm_return_type = convertType(func.returnType);
    std::vector<llvm::Type*> llvm_args;
    for (auto & arg : func.args)
    {
      llvm_args.push_back(convertType(arg.second));
    }
    llvm::FunctionType* func_type = 
      llvm::FunctionType::get(llvm_return_type, llvm_args, false);
    auto local_llvm_func = llvm::Function::Create(
        func_type, 
        llvm::Function::ExternalLinkage, 
        func.name, 
        LLVM_module_.get());
    
    // set arguments name
    auto arg_iter = local_llvm_func->arg_begin();
    for (size_t i = 0; i < func.args.size(); i++)
    {
      arg_iter->setName(func.args[i].first);

      arg_iter++;
    }
    // add to llvm module - end 
    // debug print
    std::string ss;
    llvm::raw_string_ostream ss2(ss);
    local_llvm_func->print(ss2);
    DEBUG_PRINT("Add function define: " + ss);
  }

  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void JLCX86Generator::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */
  globalContext.currentFrameName = fn_def->ident_; // set context to the current function


  // reset inner variables before visiting the function body
  block_var_map_list.clear();

  // create a new block 
  DEBUG_PRINT("Create the entry block")
  auto & func = globalContext.currentFrame();
  func.newBlock();
  addBlockVarMap();
  addBlockStackMap();
  addBlockVarInfoMap (); // this is used to store the arguments
  // add a new block to the function
  auto llvm_func = LLVM_module_->getFunction(func.name);
  llvm::BasicBlock* entry = 
    llvm::BasicBlock::Create(*LLVM_Context_, "entry", llvm_func);
  LLVM_builder_->SetInsertPoint(entry);
  

  DEBUG_PRINT("init args");
 
  // if the block is the function body, we need to add the arguments to the block
  if (func.blk->parent == nullptr)
  {

    for (auto & arg : func.args)
    {
      auto arg_iter = llvm_func->arg_begin();// get the value* of the argument
      for (size_t i = 0; i < func.args.size(); i++)
      {
        if (arg.first == std::string(arg_iter->getName()))
        {  
          auto alloca = LLVM_builder_->CreateAlloca(convertType(arg.second), nullptr, arg.first);
          LLVM_builder_->CreateStore(arg_iter, alloca);
          addVarToBlockMap(arg.first, alloca);
            // set x86 information
          addVarToStackMap(arg.first, alloca);
          int stkptr = getStackTop();
          
          addVarInfoToBlockMap(arg.first, alloca, stkptr,"");
          
          auto reg = popArgFromFunctionMap(arg.second);

          //std::cout << "  mov dword [rbp" << stkptr << "], "<< reg << std::endl;
          //restore the register availability
          updateRegisterAvailability(reg, true);

          //push the inst to x86_code_inst
          std::stringstream ss;
          ss << "  mov dword [rbp" << stkptr << "], "<< reg;
          std::string inst = ss.str();
          x86_function_map[globalContext.currentFrameName].push_back(inst);
         
          break;
        }
        arg_iter++;
      }
    }
      // after init args to stack, restore the function arg map
    restoreFunctionArgQueue();
  }




  // cotinue to iterate the function body
  if (fn_def->blk_) fn_def->blk_->accept(this);

  // after visiting the block
  //for x86 assembly generator
  //std::cout << globalContext.currentFrameName << ":" << std::endl;
  //std::cout << "  push rbp" << std::endl;
  //std::cout << "  mov rbp, rsp" << std::endl;
  if(function_call_map[globalContext.currentFrameName]==true){
    int blktop = getStackTop();
    //std::cout << "  sub rsp, " << ((-blktop)/16+1)*16 << std::endl;
    std::stringstream ss;
    ss << ((-blktop)/16+1)*16;
    std::string sub_rsp_value = ss.str();
    x86_function_map[globalContext.currentFrameName].insert(x86_function_map[globalContext.currentFrameName].begin(),"  sub rsp, "+sub_rsp_value);
  }


  // store the x86 code to the x86_code_vector
  x86_function_map[globalContext.currentFrameName].insert(x86_function_map[globalContext.currentFrameName].begin(),"  mov rbp, rsp");
  x86_function_map[globalContext.currentFrameName].insert(x86_function_map[globalContext.currentFrameName].begin(),"  push rbp");
  if(globalContext.currentFrameName=="main"){
    x86_function_map[globalContext.currentFrameName].insert(x86_function_map[globalContext.currentFrameName].begin(),"_start:");
  }else{
    x86_function_map[globalContext.currentFrameName].insert(x86_function_map[globalContext.currentFrameName].begin(),globalContext.currentFrameName + ":");
  }


  // check if the predecessor block is terminated
  if (LLVM_builder_->GetInsertBlock()->getTerminator() == nullptr)
  {
    // if the block is not terminated, we need to add a return statement
    if (func.returnType == VOID)
    {
      LLVM_builder_->CreateRetVoid();
    }
    else
    {
     ERRPR_HANDLE("function block does not have a return statement");
    }
  }

    // print x86 code to the asm file

    for(const auto & ins : x86_function_map[globalContext.currentFrameName]){
      outfile << ins << std::endl;
    }
  
  

  // release the block
  DEBUG_PRINT("release the entry block");
  func.releaseBlock();
  removeBlockVarMap();
  removeBlockStackMap();
  removeBlockVarInfoMap();
}

void JLCX86Generator::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */
  // this part is same as the type checker,
  // will add all the arguments to the function
  // but does not check the types of the arguments in generator
    if (argument->type_) argument->type_->accept(this);
    DEBUG_PRINT("\tArgument name: " + argument->ident_ + 
      "\tArgument type: " + to_string(temp_type));
    Frame& func = globalContext.getFrame(globalContext.currentFrameName);
    // add the argument to the function
    func.addArg(argument->ident_, temp_type);
}

void JLCX86Generator::visitBlock(Block *block)
{
  /* Code For Block Goes Here */
  DEBUG_PRINT( "[" + GeneratorName  +"]" + " visiting Block");
  DEBUG_PRINT("go through the block")

  if (block->liststmt_) block->liststmt_->accept(this);
}

void JLCX86Generator::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */
  //x86 assembly generator for empty
  //std::cout << "  nop" << std::endl;
  x86_function_map[globalContext.currentFrameName].push_back("  nop");
}

void JLCX86Generator::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */
  DEBUG_PRINT( "[" + GeneratorName  +"]" + " visiting BStmt");
  auto & func = globalContext.currentFrame();
  func.newBlock();
  addBlockVarMap(); // this 

  if (b_stmt->blk_) b_stmt->blk_->accept(this);
  // release the block
  DEBUG_PRINT("release block");
  func.releaseBlock();
  removeBlockVarMap();
}

void JLCX86Generator::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */
  if (decl->type_) decl->type_->accept(this);
  auto temp_decl_type = temp_type;
  for (auto & item : *(decl->listitem_)){
    temp_type = temp_decl_type; // !! this is important, as the type will pase to the next level
    item->accept(this);
  }
  

}

void JLCX86Generator::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);
  // llvm_temp_value_ is set by next level (accept)
  auto var = getVarFromBlockMap(ass->ident_);

  LLVM_builder_->CreateStore(llvm_temp_value_, var);
  
  auto varInfo = getVarInfoFromBlockMap(ass->ident_);

  //change the Value* of varInfo
  varInfo->value = var;

  //get the stack location from varInfo
  auto stkptr = varInfo->stack_location;

  
  if(x86_temp_value_type == "Imm"){
    //std::cout << "  mov dword [rbp" << stkptr << "], " << x86_temp_value<< std::endl;
    // push the inst to x86_code_inst
    std::stringstream ss;
    ss << "  mov dword [rbp" << stkptr << "], " << x86_temp_value;
    std::string inst = ss.str();
    x86_function_map[globalContext.currentFrameName].push_back(inst);

  } else if(x86_temp_value_type == "Var"){
    //get the varInfo

    auto subvarInfo = getVarInfoFromBlockMap(x86_temp_value);
    //find the coorsponding reg of this var
    //std::cout << "  mov dword [rbp" << stkptr << "], " << subvarInfo->register_name<< std::endl;

    //push the inst to x86_code _inst
    std::stringstream ss;
    ss <<  "  mov dword [rbp" << stkptr << "], " << subvarInfo->register_name;
    std::string inst =ss.str();
    x86_function_map[globalContext.currentFrameName].push_back(inst);

    //retore the avaibility of this reg
    updateRegisterAvailability(subvarInfo->register_name, true);

  } else if(x86_temp_value_type == "Fun"){
    if(temp_type == DOUB){
      //std::cout << "  movq rax, xmm0"<< std::endl;
      //std::cout << "  mov dword [rbp" << stkptr << "], " << "rax"<< std::endl;
    }
    //std::cout << "  mov dword [rbp" << stkptr << "], " << "eax"<< std::endl;
    //push the inst to x86_code_inst
    x86_function_map[globalContext.currentFrameName].push_back("  mov dword [rbp" + std::to_string(stkptr) + "], eax");
  }
  
  
}

void JLCX86Generator::visitArrayAss(ArrayAss *array_ass)
{
  /* Code For ArrayAss Goes Here */

  if (array_ass->expr_1) array_ass->expr_1->accept(this);
  if (array_ass->expr_2) array_ass->expr_2->accept(this);

}

void JLCX86Generator::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  // visitIdent(incr->ident_);
  // x++ -> x=x+1
  auto var = getVarFromBlockMap(incr->ident_);
  // load x must but int type, it will be check by the typer checker
  auto load = LLVM_builder_->CreateLoad(
      convertType(INT), var, incr->ident_);
  // add with 1 
  auto op = LLVM_builder_->CreateAdd(
        load, 
        llvm::ConstantInt::get(*LLVM_Context_, 
            llvm::APInt(32, 1)),
        "add");
  // store
  LLVM_builder_->CreateStore(op, var);
}

void JLCX86Generator::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  // visitIdent(decr->ident_);
  // x-- -> x=x-1
  auto var = getVarFromBlockMap(decr->ident_);
  // load x must but int type, it will be check by the typer checker
  auto load = LLVM_builder_->CreateLoad(
      convertType(INT), var, decr->ident_);
  // sub 1 
  auto op = LLVM_builder_->CreateSub(
        load, 
        llvm::ConstantInt::get(*LLVM_Context_, 
            llvm::APInt(32, 1)),
        "sub");
  // store
  LLVM_builder_->CreateStore(op, var);
  // store does not return a value, 
  // so we do not need to set llvm_temp_value_
}

void JLCX86Generator::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */
  DEBUG_PRINT("visitRet");
  if (ret->expr_) ret->expr_->accept(this);
  // add llvm return 
  LLVM_builder_->CreateRet(llvm_temp_value_);

  //for x86 assembly generator
  if(x86_temp_value_type=="Imm"){
    if(temp_type == DOUB){
      //std::cout << "  movq xmm0, " << x86_temp_value << std::endl;
      //push the inst to x86_code_inst
      x86_function_map[globalContext.currentFrameName].push_back("  movq xmm0, " + x86_temp_value);
    } else{
      //std::cout << "  mov eax, " << x86_temp_value << std::endl;
      //push the inst to x86_code_inst
      x86_function_map[globalContext.currentFrameName].push_back("  mov eax, " + x86_temp_value);
    }
  } else if(x86_temp_value_type == "Var"){
    auto varInfo = getVarInfoFromBlockMap(x86_temp_value);
    if(temp_type == DOUB){
      if(varInfo->register_name != "xmm0"){
        //std::cout << "  movq xmm0, " << varInfo->register_name << std::endl;
        //set the availability of this reg
        updateRegisterAvailability("xmm0", false);
        //push the inst to x86_code_inst
        x86_function_map[globalContext.currentFrameName].push_back("  movq xmm0, " + varInfo->register_name);
      }
    } else{
      if(varInfo->register_name != "eax"){
        //std::cout << "  mov eax, " << varInfo->register_name << std::endl; 
        //set the availability of this reg
        updateRegisterAvailability("eax", false);
        //push the inst to x86_code_inst
        x86_function_map[globalContext.currentFrameName].push_back("  mov eax, " + varInfo->register_name);
      }
      
    }
    //restore
    updateRegisterAvailability(varInfo->register_name, true);
  } else if(x86_temp_value_type == "Fun"){//TODO func return
    // if(temp_type == DOUB){
    //   //std::cout << "  movq xmm0, xmm0" << std::endl;
    // } else{
    //   //std::cout << "  mov eax, eax" << std::endl;
    // }
  }

  // return
  if(globalContext.currentFrameName!="main"){
    if(function_call_map[globalContext.currentFrameName]==true){
      //std::cout << "  leave"<< std::endl;
      //std::cout << "  ret" << std::endl;
      //push the inst to x86_code_inst
      x86_function_map[globalContext.currentFrameName].push_back("  leave");
      x86_function_map[globalContext.currentFrameName].push_back("  ret");
    } else{
      //std::cout << "  pop rbp"<< std::endl;
      //std::cout << "  ret" << std::endl;
      //push the inst to x86_code_inst
      x86_function_map[globalContext.currentFrameName].push_back("  pop rbp");
      x86_function_map[globalContext.currentFrameName].push_back("  ret");
    }
  } else{
    //std::cout << "  mov edi, eax"<< std::endl;
    //std::cout << "  mov eax, 60"<< std::endl;
    //std::cout << "  syscall"<< std::endl;
    //push the inst to x86_code_inst
    x86_function_map[globalContext.currentFrameName].push_back("  mov edi, eax");
    x86_function_map[globalContext.currentFrameName].push_back("  mov eax, 60");
    x86_function_map[globalContext.currentFrameName].push_back("  syscall");
  }
}

void JLCX86Generator::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */
  LLVM_builder_->CreateRetVoid();
  DEBUG_PRINT("visitVRet");
}

void JLCX86Generator::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */
  auto current_block = LLVM_builder_->GetInsertBlock();
  auto parent = current_block->getParent();
  auto cond_true_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "cond.true", parent);
  auto cond_end_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "cond.end", parent);

  if (cond->expr_) cond->expr_->accept(this);
  auto expr_llvm_value = llvm_temp_value_;

  LLVM_builder_->CreateCondBr(expr_llvm_value, cond_true_block, cond_end_block);
  LLVM_builder_->SetInsertPoint(cond_true_block);

  auto func = globalContext.currentFrame();
  func.newBlock(); // just logic block, no need to create a label
  addBlockVarMap();// just logic block, no need to create a label

  if (cond->stmt_) cond->stmt_->accept(this);
  auto stmt_llvm_value = llvm_temp_value_;

  func.releaseBlock(); // release the logic block
  removeBlockVarMap(); // release the logic block

  // if the block is not terminated, we need to jump to the end block
  if (LLVM_builder_->GetInsertBlock()->getTerminator() == nullptr)
  {
    LLVM_builder_->CreateBr(cond_end_block); 
    DEBUG_PRINT("Branch:" + std::string(LLVM_builder_->GetInsertBlock()->getName()) 
      +" is not terminated by return" );
  }
  LLVM_builder_->SetInsertPoint(cond_end_block); 
}

void JLCX86Generator::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */
  auto current_block = LLVM_builder_->GetInsertBlock();
  auto parent = current_block->getParent();
  auto cond_true_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "cond.true", parent);
  auto cond_else_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "cond.else", parent);
  auto cond_end_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "cond.end", parent);
  

  if (cond_else->expr_) cond_else->expr_->accept(this);
  auto expr_llvm_value = llvm_temp_value_;

  LLVM_builder_->CreateCondBr(expr_llvm_value, cond_true_block, cond_else_block);
  LLVM_builder_->SetInsertPoint(cond_true_block);

  auto func = globalContext.currentFrame();
  func.newBlock(); // just logic block, no need to create a label
  addBlockVarMap();// just logic block, no need to create a label
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  auto stmt_1_llvm_value = llvm_temp_value_;
  func.releaseBlock(); // release the logic block
  removeBlockVarMap(); // release the logic block

  bool need_end_block = false;
  // if the block is not terminated, we need to jump to the end block
  if (cond_true_block->getTerminator() == nullptr)
  {
    LLVM_builder_->CreateBr(cond_end_block);
    need_end_block = true;
    DEBUG_PRINT("Branch IF:" + std::string(cond_true_block->getName()) 
      +" is not terminated by return" );
  }

  LLVM_builder_->SetInsertPoint(cond_else_block);

  func.newBlock(); // just logic block, no need to create a label
  addBlockVarMap();// just logic block, no need to create a label
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);
  auto stmt_2_llvm_value = llvm_temp_value_;
  func.releaseBlock(); // release the logic block
  removeBlockVarMap(); // release the logic block

  // if the block is not terminated, we need to jump to the end block
  if (cond_else_block->getTerminator() == nullptr)
  {
    LLVM_builder_->CreateBr(cond_end_block);
    need_end_block = true;
    DEBUG_PRINT("Branch ELSE:" + std::string(cond_else_block->getName()) 
      +" is not terminated by return" );
  } 
  if (need_end_block){ 
    // if one of the block is not terminated, we need to jump to the end block
    LLVM_builder_->SetInsertPoint(cond_end_block);
  } else{
    // remove the end block
    cond_end_block->eraseFromParent();
  }
  
}

void JLCX86Generator::visitWhile(While *while_)
{
  /* Code For While Goes Here */
  auto current_block = LLVM_builder_->GetInsertBlock();
  auto parent = current_block->getParent();
  auto cond_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "while.cond", parent);
  auto loop_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "while.loop", parent);
  auto end_block = llvm::BasicBlock::Create(
      *LLVM_Context_, "while.end", parent);

  // jump to the cond block
  LLVM_builder_->CreateBr(cond_block);
  LLVM_builder_->SetInsertPoint(cond_block);
  if (while_->expr_) while_->expr_->accept(this);
  auto expr_llvm_value = llvm_temp_value_;
  // jump to the loop block or end block
  LLVM_builder_->CreateCondBr(expr_llvm_value, loop_block, end_block);
  LLVM_builder_->SetInsertPoint(loop_block);
  // create a new block for the loop
  auto func = globalContext.currentFrame();
  func.newBlock(); // just logic block, no need to create a label
  addBlockVarMap();// just logic block, no need to create a label
  if (while_->stmt_) while_->stmt_->accept(this);
  auto stmt_llvm_value = llvm_temp_value_;
  LLVM_builder_->CreateBr(cond_block);
  func.releaseBlock(); // release the logic block
  removeBlockVarMap(); // release the logic block
  // end block
  LLVM_builder_->SetInsertPoint(end_block);
}


void JLCX86Generator::visitForBlk(ForBlk *for_blk)
{
  /* Code For ForBlk Goes Here */

  if (for_blk->type_) for_blk->type_->accept(this);
  if (for_blk->item_) for_blk->item_->accept(this);
  if (for_blk->stmt_) for_blk->stmt_->accept(this);

}


void JLCX86Generator::visitForLoop(ForLoop *for_loop)
{
  /* Code For ForLoop Goes Here */

  if (for_loop->stmt_) for_loop->stmt_->accept(this);

}

void JLCX86Generator::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void JLCX86Generator::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */
  visitIdent(no_init->ident_);
  auto temp_decl_type = temp_type; // !this type is passed from top level
  auto & frame = globalContext.currentFrame();
  frame.addVar(no_init->ident_, temp_decl_type);

  
  llvm::Constant* init_val = nullptr;
  switch (temp_decl_type)
  {
  case INT:
    init_val = llvm::ConstantInt::get(*LLVM_Context_, llvm::APInt(32, 0));
    break;
  case DOUB:
    init_val = llvm::ConstantFP::get(*LLVM_Context_, llvm::APFloat(0.0));
    break;
  default:
    break;
  }
  /*todo: this should be an optional part, 
    which initialize the variable when allocates the memory
    now we just first allocate the memory, and then use sort to initialize the memory
  */ 
  // auto alloca = LLVM_builder_->CreateAlloca(convertType(temp_type), init_val, no_init->ident_);
  auto alloca = LLVM_builder_->CreateAlloca(convertType(temp_type), nullptr, no_init->ident_);
  addVarToBlockMap(no_init->ident_, alloca);
  if (init_val != nullptr)
  {
    LLVM_builder_->CreateStore(init_val, alloca);
    //@TODO: a better way to add comments
    llvm::MDNode* N = llvm::MDNode::get(*LLVM_Context_, 
      llvm::MDString::get(*LLVM_Context_, "Default value: 0"));
    alloca->setMetadata("comment", N);
  }
}

void JLCX86Generator::visitInit(Init *init)
{
  /* Code For Init Goes Here */
  visitIdent(init->ident_);
  auto temp_decl_type = temp_type; // !this type is passed from top level
  auto & frame = globalContext.currentFrame();
  

  if (init->expr_) init->expr_->accept(this);
  
  // why we add the var after xx->accept(this)?
  // consider the case:  int x=1; {int x = x;}
  frame.addVar(init->ident_, temp_decl_type);
  
  
  auto alloca = LLVM_builder_->CreateAlloca(convertType(temp_decl_type), nullptr, init->ident_);
  // add the variable to the block map
  addVarToBlockMap(init->ident_, alloca);
  addVarToStackMap(init->ident_, alloca);
  
  // store a constant value to the memory
  LLVM_builder_->CreateStore(llvm_temp_value_, alloca);

 

  //for x86 assembly generator
  // update the stack frame space change after each variable init
  if (temp_decl_type == INT)
  {

    //get the stack top
    int stkptr = getStackTop();
    //std::cout << "  mov dword [rbp" << stkptr << "], " << x86_temp_value<< std::endl;
    addVarInfoToBlockMap(init->ident_, alloca, stkptr,"");

    //push the inst to x86_code_inst
    std::stringstream ss;
    ss << "  mov dword [rbp" << stkptr << "], " << x86_temp_value;
    std::string inst = ss.str();
    x86_function_map[globalContext.currentFrameName].push_back(inst);
  }
  else if (temp_decl_type == DOUB)
  {
    int stkptr = getStackTop();
    //std::cout << "  movsd QWORD PTR [rbp" << stkptr<< "], " << x86_temp_value << std::endl;
    addVarInfoToBlockMap(init->ident_, alloca, stkptr,"");

    //push the inst to x86_code_inst
    std::stringstream ss;
    ss << "  movsd QWORD PTR [rbp" << stkptr << "], " << x86_temp_value;
    std::string inst = ss.str();
    x86_function_map[globalContext.currentFrameName].push_back(inst);
  }
}

void JLCX86Generator::visitInitElem(InitElem *init_elem)
{
  /* Code For InitElem Goes Here */

  visitIdent(init_elem->ident_);
  if (init_elem->expr_) init_elem->expr_->accept(this);

}

void JLCX86Generator::visitInt(Int *int_)
{
  /* Code For Int Goes Here */
  temp_type = INT;

}

void JLCX86Generator::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */
  temp_type = DOUB;
}

void JLCX86Generator::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */
  temp_type = BOOL;
}

void JLCX86Generator::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */
  temp_type = VOID;
}

void JLCX86Generator::visitIntArray(IntArray *int_array)
{
  /* Code For IntArray Goes Here */
  temp_type = INTARRAY;

}

void JLCX86Generator::visitDoubArray(DoubArray *doub_array)
{
  /* Code For DoubArray Goes Here */
  temp_type = DOUBARRAY;

}

void JLCX86Generator::visitBoolArray(BoolArray *bool_array)
{
  /* Code For BoolArray Goes Here */
  temp_type = BOOLARRAY;

}

void JLCX86Generator::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void JLCX86Generator::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */
  auto & frame = globalContext.currentFrame();
  temp_type = frame.getVarType(e_var->ident_);
  // visitIdent(e_var->ident_);
  
  // when we access a variable, we need to load the value from the memory
  // llvm load 
  llvm::Value* var = getVarFromBlockMap(e_var->ident_);
  setLLVMTempValue( LLVM_builder_->CreateLoad(convertType(temp_type), var, e_var->ident_));

  x86_temp_value = e_var->ident_;
  x86_temp_value_type = "Var";
  //for x86 assembly generator
  auto varInfo = getVarInfoFromBlockMap(e_var->ident_);
  // get the location from varInfo
  auto stkloc = varInfo->stack_location;

  //check
  // allocate the stack location to one register, for example, eax , and update the the status from true to false in register_map
  if (temp_type == INT)
  {
    auto reg = checkIntRegisterAvailability();

    if (reg =="")
    {
      std::cerr << "ERROR: no available register for int type\n";
      exit(1);
    }
    else
    {
      //std::cout << "  mov " << reg << ", dword [rbp" << stkloc << "]" << std::endl;
      updateRegisterAvailability(reg, false);
      updateVarInfoRegisterName(e_var->ident_, reg);
      updateRegisterValue(var, reg);

      //push the inst to x86_code_inst
      std::stringstream ss;
      ss << "  mov " << reg << ", dword [rbp" << stkloc << "]";
      std::string inst = ss.str();
      x86_function_map[globalContext.currentFrameName].push_back(inst);
    }
  }
  else if (temp_type == DOUB)
  {
    auto reg = checkDoubleRegisterAvailability();

    if (reg == "")
    {
      std::cerr << "ERROR: no available register for double type\n";
      exit(1);
    }
    else
    {
      //std::cout << "  movsd " << reg << ", QWORD PTR [rbp" << stkloc << "]" << std::endl;
      updateRegisterAvailability(reg, false);
      updateVarInfoRegisterName(e_var->ident_, reg);
      updateRegisterValue(var, reg);

      //push the inst to x86_code_inst
      std::stringstream ss;
      ss << "  movsd " << reg << ", QWORD PTR [rbp" << stkloc << "]";
      std::string inst = ss.str();
      x86_function_map[globalContext.currentFrameName].push_back(inst);

    }
  }




}

void JLCX86Generator::visitEArrayNew(EArrayNew *e_array_new)
{
  /* Code For EArrayNew Goes Here */

  if (e_array_new->expr_) e_array_new->expr_->accept(this);
  if(temp_type != INT){
    std::cerr << "ERROR: can just declare a array of [] int type\n";
    exit(1);
  }
  llvm::Value* var = llvm_temp_value_;
  
  //setLLVMTempValue( LLVM_builder_->CreateLoad(convertType(INT), var, "tmp"));
  setLLVMTempValue( var);
  if (e_array_new->type_) e_array_new->type_->accept(this);
  if(temp_type == VOID){
    std::cerr << "ERROR: cannot declare a array variable with void type\n";
    exit(1);
  }
  if(temp_type == INT) temp_type = INTARRAY;
  if(temp_type == DOUB) temp_type = DOUBARRAY;
  if(temp_type == BOOL) temp_type = BOOLARRAY;
}

void JLCX86Generator::visitEArrayLen(EArrayLen *e_array_len)
{
  /* Code For EArrayLen Goes Here */

  if (e_array_len->expr_1) e_array_len->expr_1->accept(this);
  if (e_array_len->expr_2) e_array_len->expr_2->accept(this);

}

void JLCX86Generator::visitEArray(EArray *e_array)
{
  /* Code For EArray Goes Here */

  if (e_array->expr_1) e_array->expr_1->accept(this);
  if (e_array->expr_2) e_array->expr_2->accept(this);

}


void JLCX86Generator::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);
  temp_type = INT;
  x86_temp_value = std::to_string(e_lit_int->integer_);
  x86_temp_value_type = "Imm";
  // llvm constant
  setLLVMTempValue( llvm::ConstantInt::get(*LLVM_Context_, llvm::APInt(32, e_lit_int->integer_)));
  
}

void JLCX86Generator::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);
  temp_type = DOUB;
  // llvm constant
  setLLVMTempValue(llvm::ConstantFP::get(*LLVM_Context_, llvm::APFloat(e_lit_doub->double_)));
}

void JLCX86Generator::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */

  temp_type = BOOL;
  // llvm constant 
  setLLVMTempValue( llvm::ConstantInt::get(*LLVM_Context_, llvm::APInt(1, 1)));

}

void JLCX86Generator::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */
  temp_type = BOOL;
  // llvm constant
  setLLVMTempValue( llvm::ConstantInt::get(*LLVM_Context_, llvm::APInt(1, 0)));
}

void JLCX86Generator::visitEApp(EApp *e_app)
{
  DEBUG_PRINT("Visit EApp: " + e_app->ident_);
  function_call_map[globalContext.currentFrameName] = true;
  /* Code For EApp Goes Here */
  std::vector<llvm::Value*> args;
  // iterate through the arguments, and collect the llvm values
  for (auto & expr : *(e_app->listexpr_))
  {
    expr->accept(this);
    args.push_back(llvm_temp_value_);

    //for x86 func call
    DEBUG_PRINT("x86 func call")
  
    if(x86_temp_value_type=="Imm"){
      auto reg = popArgFromFunctionMap(temp_type);
      //std::cout << "  mov " << reg << ", " << x86_temp_value << std::endl;
      updateRegisterAvailability(reg, false);
      //push the inst to x86_code_inst
      std::stringstream ss;
      ss << "  mov " << reg << ", " << x86_temp_value;
      std::string inst = ss.str();
      x86_function_map[globalContext.currentFrameName].push_back(inst);
    } else if(x86_temp_value_type == "Var"){
      //get the varInfo
      auto subvarInfo = getVarInfoFromBlockMap(x86_temp_value);
      auto reg = popArgFromFunctionMap(temp_type);
      //find the coorsponding reg of this var
      //std::cout << "  mov " << reg << ", " << subvarInfo->register_name  << std::endl;
      
      updateRegisterAvailability(subvarInfo->register_name, true);
      updateRegisterAvailability(reg, false);
      //push the inst to x86_code_inst
      std::stringstream ss;
      ss << "  mov " << reg << ", " << subvarInfo->register_name ;
      std::string inst = ss.str();
      x86_function_map[globalContext.currentFrameName].push_back(inst);
    } else if(x86_temp_value_type == "Fun"){//TODO
      // if(temp_type == DOUB){
      //   //std::cout << "  movq rax, xmm0"<< std::endl;
      //   //std::cout << "  mov " << reg << ", rax"<< std::endl;
      // }
      // //std::cout << "  mov " << reg << ", eax"<< std::endl;
    }
  }
  // add llvm function call
  auto llvm_func = LLVM_module_->getFunction(e_app->ident_);
  // check if the return type is void
  std::string tag = "";
  DEBUG_PRINT("EApp check return type")
  if (!llvm_func->getReturnType()->isVoidTy())
  {
    DEBUG_PRINT("EApp return type is not void")
    // if return type is void, then we have to pass empty string as tag
    tag = e_app->ident_;
  }
  DEBUG_PRINT("EApp create call")
  setLLVMTempValue( LLVM_builder_->CreateCall(llvm_func, args, tag));
  DEBUG_PRINT("Call function: " + e_app->ident_);


  //x86 func call assembly generator
  //std::cout << "  call " << e_app->ident_ << std::endl;

  //push the inst to x86_code_inst
  std::stringstream ss;
  ss << "  call " << e_app->ident_;
  std::string inst = ss.str();
  x86_function_map[globalContext.currentFrameName].push_back(inst);


  x86_temp_value_type = "Fun";  
}

void JLCX86Generator::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */
  temp_type = STRING;
  
  // check if the string is already in the global context
  // @TODO: this is not a good way to store the string, 
  //        using llvm api to check if a string is already in the global context
  // why we convert string to id? Considering the case a very long string.
  static int global_string_id = 0;
  static std::map<std::string, int> string_id_map;
  static std::map<int, llvm::GlobalVariable*> global_sid_var_map;
  
  int id = -1;
  if (string_id_map.find(e_string->string_) == string_id_map.end())
  {
    string_id_map[e_string->string_] = global_string_id;
    global_string_id++;
  }
  id = string_id_map[e_string->string_];
  if (global_sid_var_map.find(id) == global_sid_var_map.end())
  {
    DEBUG_PRINT("Add string to global context: " 
      + e_string->string_ + " id: " + std::to_string(id));

    auto global_var = new llvm::GlobalVariable(
      *LLVM_module_, 
      llvm::ArrayType::get(llvm::Type::getInt8Ty(*LLVM_Context_), e_string->string_.size() + 1),
      true,
      llvm::GlobalValue::PrivateLinkage,
      llvm::ConstantDataArray::getString(*LLVM_Context_, e_string->string_),
      "str" + std::to_string(id)
    );
    global_sid_var_map[id] = global_var;
  }

  setLLVMTempValue( global_sid_var_map[id]);
}

void JLCX86Generator::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);
  // llvm neg
  // if value is int, then we use CreateNeg
  if(llvm_temp_value_->getType()->isIntegerTy())
  {
    setLLVMTempValue( LLVM_builder_->CreateNeg(llvm_temp_value_));
  }
  else
  {
    setLLVMTempValue( LLVM_builder_->CreateFNeg(llvm_temp_value_));
  }
}

void JLCX86Generator::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);
  // llvm not
  setLLVMTempValue(LLVM_builder_->CreateNot(llvm_temp_value_));

}

void JLCX86Generator::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  auto expr_1_llvm_value = llvm_temp_value_;
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  auto local_op = temp_op;
  if (e_mul->expr_2) e_mul->expr_2->accept(this);
  auto expr_2_llvm_value = llvm_temp_value_;

  switch (local_op)
  {
  case eMUL:
    // if value is int, then we use CreateMul
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateMul(
          expr_1_llvm_value, expr_2_llvm_value, "mul"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFMul(
          expr_1_llvm_value, expr_2_llvm_value, "mul"));
    }
    break;
  case eDIV:
    // if value is int, then we use CreateSDiv
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateSDiv(
          expr_1_llvm_value, expr_2_llvm_value, "div"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFDiv(
          expr_1_llvm_value, expr_2_llvm_value, "div"));
    }
    break;
  case eMOD:
    // only for int
    setLLVMTempValue( LLVM_builder_->CreateSRem(
        expr_1_llvm_value, expr_2_llvm_value, "mod"));
    break;
  default:
    ERRPR_HANDLE("unknown EMUL operation")
    break;
  }
}

void JLCX86Generator::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  auto expr_1_llvm_value = llvm_temp_value_;
  if (e_add->addop_) e_add->addop_->accept(this);
  auto local_op = temp_op;
  if (e_add->expr_2) e_add->expr_2->accept(this);
  auto expr_2_llvm_value = llvm_temp_value_;

  switch (local_op)
  {
  case eADD:
    // if value is int, then we use CreateAdd
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateAdd(
          expr_1_llvm_value, expr_2_llvm_value, "add"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFAdd(
          expr_1_llvm_value, expr_2_llvm_value, "add"));
    }
    break;
  case eSUB:
    // if value is int, then we use CreateSub
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateSub(
          expr_1_llvm_value, expr_2_llvm_value, "sub"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFSub(
          expr_1_llvm_value, expr_2_llvm_value, "sub"));
    }
    break;
  default:
    ERRPR_HANDLE("unknown EADD operation")
    break;
  }

}

void JLCX86Generator::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */
  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  auto expr_1_llvm_value = llvm_temp_value_;
  if (e_rel->relop_) e_rel->relop_->accept(this);
  auto local_op = temp_op;
  if (e_rel->expr_2) e_rel->expr_2->accept(this);
  auto expr_2_llvm_value = llvm_temp_value_;

  switch (local_op)
  {
  case eLT:
    // if value is int, then we use CreateICmpSLT
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpSLT(
          expr_1_llvm_value, expr_2_llvm_value, "lt"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpOLT(
          expr_1_llvm_value, expr_2_llvm_value, "lt"));
    }
    break;
  case eLE:
    // if value is int, then we use CreateICmpSLE
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpSLE(
          expr_1_llvm_value, expr_2_llvm_value, "le"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpOLE(
          expr_1_llvm_value, expr_2_llvm_value, "le"));
    }
    break;
  case eGT:
    // if value is int, then we use CreateICmpSGT
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpSGT(
          expr_1_llvm_value, expr_2_llvm_value, "gt"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpOGT(
          expr_1_llvm_value, expr_2_llvm_value, "gt"));
    }
    break;
  case eGE:
    // if value is int, then we use CreateICmpSGE
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpSGE(
          expr_1_llvm_value, expr_2_llvm_value, "ge"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpOGE(
          expr_1_llvm_value, expr_2_llvm_value, "ge"));
    }
    break;
  case eEQ:
    // if value is int, then we use CreateICmpEQ
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpEQ(
          expr_1_llvm_value, expr_2_llvm_value, "eq"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpOEQ(
          expr_1_llvm_value, expr_2_llvm_value, "eq"));
    }
    break;
  case eNE:
    // if value is int, then we use CreateICmpNE
    if(expr_1_llvm_value->getType()->isIntegerTy())
    {
      setLLVMTempValue( LLVM_builder_->CreateICmpNE(
          expr_1_llvm_value, expr_2_llvm_value, "ne"));
    }
    else
    {
      setLLVMTempValue( LLVM_builder_->CreateFCmpONE(
          expr_1_llvm_value, expr_2_llvm_value, "ne"));
    }
    break;
  default:
    ERRPR_HANDLE("unknown EREL operation")
    break;
  }
}

void JLCX86Generator::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */
  auto current_block = LLVM_builder_->GetInsertBlock();
  auto parent = current_block->getParent();
  auto and_true_block = llvm::BasicBlock::Create(*LLVM_Context_, "and.true", parent);
  auto and_end_block = llvm::BasicBlock::Create(*LLVM_Context_, "and.end", parent);

  if (e_and->expr_1) e_and->expr_1->accept(this);
  auto expr_1_llvm_value = llvm_temp_value_;
  // short-circui evaluation
  // if the first expression is false, 
  // then we do not need to evaluate the second expression
  // @todo: how to do this in llvm ?

  LLVM_builder_->CreateCondBr(expr_1_llvm_value, and_true_block, and_end_block);
  LLVM_builder_->SetInsertPoint(and_true_block);
  if (e_and->expr_2) e_and->expr_2->accept(this);
  auto expr_2_llvm_value = llvm_temp_value_;

  LLVM_builder_->CreateBr(and_end_block);
  LLVM_builder_->SetInsertPoint(and_end_block);
  llvm::PHINode* phi = LLVM_builder_->CreatePHI(
      llvm::Type::getInt1Ty(*LLVM_Context_), 2, "and");
  phi->addIncoming(expr_1_llvm_value, current_block);

  // why we dont use and_true_block as the predecessor block?
  // consider the case: 1 == a && 1 <= a && 1 >= a
  auto block_of_expr_2 = getBlockOfValue(expr_2_llvm_value);

  phi->addIncoming(expr_2_llvm_value, block_of_expr_2);
  setLLVMTempValue( phi);

  // reset the block
  // LLVM_builder_->SetInsertPoint(current_block);  @todo: do we really need this?
}

void JLCX86Generator::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */
  auto current_block = LLVM_builder_->GetInsertBlock();
  auto parent = current_block->getParent();
  auto or_false_block = llvm::BasicBlock::Create(*LLVM_Context_, "or.false", parent);
  auto or_end_block = llvm::BasicBlock::Create(*LLVM_Context_, "or.end", parent);

  if (e_or->expr_1) e_or->expr_1->accept(this);
  auto expr_1_llvm_value = llvm_temp_value_;
  // if the first expression is true, then we do not need to evaluate the second expression

  LLVM_builder_->CreateCondBr(expr_1_llvm_value, or_end_block, or_false_block);
  LLVM_builder_->SetInsertPoint(or_false_block);

  if (e_or->expr_2) e_or->expr_2->accept(this);
  auto expr_2_llvm_value = llvm_temp_value_;

  LLVM_builder_->CreateBr(or_end_block);
  LLVM_builder_->SetInsertPoint(or_end_block);
  llvm::PHINode* phi = LLVM_builder_->CreatePHI(
      llvm::Type::getInt1Ty(*LLVM_Context_), 2, "or");
  
  phi->addIncoming(expr_1_llvm_value, current_block);

  auto block_of_expr_2 = getBlockOfValue(expr_2_llvm_value);
  phi->addIncoming(expr_2_llvm_value,or_false_block);
  setLLVMTempValue( phi);

  // reset the block
  // LLVM_builder_->SetInsertPoint(current_block);  @todo: do we really need this?
}

void JLCX86Generator::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */
  temp_op = eADD;
}

void JLCX86Generator::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */
  temp_op = eSUB;
}

void JLCX86Generator::visitTimes(Times *times)
{
  /* Code For Times Goes Here */
  temp_op = eMUL;
}

void JLCX86Generator::visitDiv(Div *div)
{
  /* Code For Div Goes Here */
  temp_op = eDIV;
}

void JLCX86Generator::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */
  temp_op = eMOD;
}

void JLCX86Generator::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */
  temp_op = eLT;
}

void JLCX86Generator::visitLE(LE *le)
{
  /* Code For LE Goes Here */
  temp_op = eLE;
}

void JLCX86Generator::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */
  temp_op = eGT;
}

void JLCX86Generator::visitGE(GE *ge)
{
  /* Code For GE Goes Here */
  temp_op = eGE;
}

void JLCX86Generator::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */
  temp_op = eEQ;
}

void JLCX86Generator::visitNE(NE *ne)
{
  /* Code For NE Goes Here */
  temp_op = eNE;
}
