/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern JLCChecker. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "JLCChecker.H"
#include "context.H"
#include "util.h"

#include <iostream>
Context globalContext;

void JLCChecker::visitProg(Prog *t) {} //abstract class
void JLCChecker::visitTopDef(TopDef *t) {} //abstract class
void JLCChecker::visitArg(Arg *t) {} //abstract class
void JLCChecker::visitBlk(Blk *t) {} //abstract class
void JLCChecker::visitStmt(Stmt *t) {} //abstract class
void JLCChecker::visitItem(Item *t) {} //abstract class
void JLCChecker::visitType(Type *t) {} //abstract class
void JLCChecker::visitExpr(Expr *t) {} //abstract class
void JLCChecker::visitAddOp(AddOp *t) {} //abstract class
void JLCChecker::visitMulOp(MulOp *t) {} //abstract class
void JLCChecker::visitRelOp(RelOp *t) {} //abstract class

void JLCChecker::visitProgram(Program *program)
{
  /* Code For Program Goes Here */
  DEBUG_PRINT("Visiting Program");
  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void JLCChecker::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */
  DEBUG_PRINT("Visiting FnDef:");
  DEBUG_PRINT("Function name: " + fn_def->ident_);

  if (fn_def->type_) fn_def->type_->accept(this);
  visitIdent(fn_def->ident_);
  if (fn_def->listarg_) fn_def->listarg_->accept(this);
  if (fn_def->blk_) fn_def->blk_->accept(this);

}

void JLCChecker::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */

  if (argument->type_) argument->type_->accept(this);
  visitIdent(argument->ident_);

}

void JLCChecker::visitBlock(Block *block)
{
  /* Code For Block Goes Here */

  if (block->liststmt_) block->liststmt_->accept(this);

}

void JLCChecker::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void JLCChecker::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}

void JLCChecker::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void JLCChecker::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);

}

void JLCChecker::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  visitIdent(incr->ident_);

}

void JLCChecker::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  visitIdent(decr->ident_);

}

void JLCChecker::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void JLCChecker::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void JLCChecker::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void JLCChecker::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void JLCChecker::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void JLCChecker::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void JLCChecker::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void JLCChecker::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void JLCChecker::visitInt(Int *int_)
{
  /* Code For Int Goes Here */


}

void JLCChecker::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */


}

void JLCChecker::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */


}

void JLCChecker::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */


}

void JLCChecker::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void JLCChecker::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void JLCChecker::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void JLCChecker::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);

}

void JLCChecker::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void JLCChecker::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void JLCChecker::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void JLCChecker::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void JLCChecker::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void JLCChecker::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void JLCChecker::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void JLCChecker::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void JLCChecker::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void JLCChecker::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void JLCChecker::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void JLCChecker::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void JLCChecker::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void JLCChecker::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void JLCChecker::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void JLCChecker::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void JLCChecker::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void JLCChecker::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void JLCChecker::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void JLCChecker::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void JLCChecker::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void JLCChecker::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void JLCChecker::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCChecker::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCChecker::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCChecker::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCChecker::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCChecker::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void JLCChecker::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void JLCChecker::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void JLCChecker::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void JLCChecker::visitString(String x)
{
  /* Code for String Goes Here */
}

void JLCChecker::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



