/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern JLCFuncDeclearationChecker. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "JLCChecker.H"
#include "context.H"
#include "util.h"

#include <iostream>
#include <string>
#include <cstdlib>

static type_enum temp_type;

void JLCFuncDeclearationChecker::visitProg(Prog *t) {} //abstract class
void JLCFuncDeclearationChecker::visitTopDef(TopDef *t) {} //abstract class
void JLCFuncDeclearationChecker::visitArg(Arg *t) {} //abstract class
void JLCFuncDeclearationChecker::visitBlk(Blk *t) {} //abstract class
void JLCFuncDeclearationChecker::visitStmt(Stmt *t) {} //abstract class
void JLCFuncDeclearationChecker::visitItem(Item *t) {} //abstract class
void JLCFuncDeclearationChecker::visitType(Type *t) {} //abstract class
void JLCFuncDeclearationChecker::visitExpr(Expr *t) {} //abstract class
void JLCFuncDeclearationChecker::visitAddOp(AddOp *t) {} //abstract class
void JLCFuncDeclearationChecker::visitMulOp(MulOp *t) {} //abstract class
void JLCFuncDeclearationChecker::visitRelOp(RelOp *t) {} //abstract class

void JLCFuncDeclearationChecker::visitProgram(Program *program)
{
  /* Code For Program Goes Here */
  DEBUG_PRINT("Visiting Program");
  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void JLCFuncDeclearationChecker::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */
  DEBUG_PRINT("Visiting FnDef:");
  DEBUG_PRINT("\tFunction name: " + fn_def->ident_);

  /* type ident ( listarg ) block */
  // check function type
  if (fn_def->type_) fn_def->type_->accept(this);
  DEBUG_PRINT("\tFunction type: " + to_string(temp_type));
  // don't need to check type_, as long as the parser is correct, otherwise it will throw an error
  // it is impossible to have a function without a type

  
  // check function name
  visitIdent(fn_def->ident_);
  // check if the function is already declared
  if(globalContext.isExistFunction(fn_def->ident_)){
    std::cerr << "ERROR: Function " << fn_def->ident_ << " is already declared" << std::endl;
    exit(1);
  }
  // add the function to the global context
  globalContext.addFrame(fn_def->ident_);
  globalContext.currentFrameName = fn_def->ident_;

  Frame& func = globalContext.getFrame(fn_def->ident_);
  func.returnType = temp_type;
  
  
  // check function arguments
  if (fn_def->listarg_) fn_def->listarg_->accept(this);

  if (fn_def->blk_) fn_def->blk_->accept(this);
}

void JLCFuncDeclearationChecker::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */
  if (argument->type_) argument->type_->accept(this);
  DEBUG_PRINT("\tArgument name: " + argument->ident_ + 
    "\tArgument type: " + to_string(temp_type));
  // check if the type is ok: case 072, void type
  if(temp_type == VOID){
    std::cerr << "ERROR: Argument " << argument->ident_ 
        << " in function:"<< globalContext.currentFrameName
        << " has void type" << std::endl;
    exit(1);
  }

  Frame& func = globalContext.getFrame(globalContext.currentFrameName);
  // check if the argument is already declared
  if(func.isExistArg(argument->ident_)){
    std::cerr << "ERROR: Argument " << argument->ident_ 
        << " in function:"<< globalContext.currentFrameName
        << " is already declared" << std::endl;
    exit(1);
  }
  // add the argument to the function
  func.addArg(argument->ident_, temp_type);

  visitIdent(argument->ident_);

}

void JLCFuncDeclearationChecker::visitBlock(Block *block)
{
  /* Code For Block Goes Here */

  if (block->liststmt_) block->liststmt_->accept(this);

}

void JLCFuncDeclearationChecker::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void JLCFuncDeclearationChecker::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}

void JLCFuncDeclearationChecker::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void JLCFuncDeclearationChecker::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  visitIdent(incr->ident_);

}

void JLCFuncDeclearationChecker::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  visitIdent(decr->ident_);

}

void JLCFuncDeclearationChecker::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void JLCFuncDeclearationChecker::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void JLCFuncDeclearationChecker::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void JLCFuncDeclearationChecker::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void JLCFuncDeclearationChecker::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void JLCFuncDeclearationChecker::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitInt(Int *int_)
{
  /* Code For Int Goes Here */
  temp_type = INT;
}

void JLCFuncDeclearationChecker::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */
  temp_type = DOUB;
}

void JLCFuncDeclearationChecker::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */
  temp_type = BOOL;

}

void JLCFuncDeclearationChecker::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */
  temp_type = VOID;

}

void JLCFuncDeclearationChecker::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void JLCFuncDeclearationChecker::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void JLCFuncDeclearationChecker::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void JLCFuncDeclearationChecker::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);

}

void JLCFuncDeclearationChecker::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void JLCFuncDeclearationChecker::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void JLCFuncDeclearationChecker::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void JLCFuncDeclearationChecker::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void JLCFuncDeclearationChecker::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void JLCFuncDeclearationChecker::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void JLCFuncDeclearationChecker::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void JLCFuncDeclearationChecker::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void JLCFuncDeclearationChecker::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void JLCFuncDeclearationChecker::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void JLCFuncDeclearationChecker::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void JLCFuncDeclearationChecker::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void JLCFuncDeclearationChecker::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void JLCFuncDeclearationChecker::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void JLCFuncDeclearationChecker::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void JLCFuncDeclearationChecker::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void JLCFuncDeclearationChecker::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void JLCFuncDeclearationChecker::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void JLCFuncDeclearationChecker::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void JLCFuncDeclearationChecker::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void JLCFuncDeclearationChecker::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void JLCFuncDeclearationChecker::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCFuncDeclearationChecker::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCFuncDeclearationChecker::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCFuncDeclearationChecker::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCFuncDeclearationChecker::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCFuncDeclearationChecker::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void JLCFuncDeclearationChecker::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void JLCFuncDeclearationChecker::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void JLCFuncDeclearationChecker::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void JLCFuncDeclearationChecker::visitString(String x)
{
  /* Code for String Goes Here */
}

void JLCFuncDeclearationChecker::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



