/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern JLCLLVMGenerator. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "JLCLLVMGenerator.H"
#include "util.h"
#include "Printer.H"

#include <iostream>
#include <string>
#include <sstream>
#include <cstdlib>

#include "llvm/Support/raw_ostream.h"

static PrintAbsyn p = PrintAbsyn();

static const std::string GeneratorName = "JLCLLVMGenerator";

/*
  this function is used to convert the type_enum to string
  @return: llvm::Type*
  @param: type_enum t
*/
llvm::Type* JLCLLVMGenerator::convertType(type_enum t){
  switch (t)
  {
  case INT:
    return llvm::Type::getInt32Ty(*LLVM_Context_);
  case DOUB:
    return llvm::Type::getDoubleTy(*LLVM_Context_);
  case BOOL:
    return llvm::Type::getInt1Ty(*LLVM_Context_);
  case VOID:
    return llvm::Type::getVoidTy(*LLVM_Context_);
  case CHAR:
    return llvm::Type::getInt8Ty(*LLVM_Context_);
  case STRING: // the atcually out is ptr not i8*, is it ok? @todo
    return llvm::Type::getInt8PtrTy(*LLVM_Context_);
  default:
    std::cerr << "Error, Unknown type:" << to_string(t) << std::endl;
    return nullptr;
  }
}

void JLCLLVMGenerator::addExternalFunc(){
  for (auto & func : globalContext.funcs)
  {
    addFuncDeclearation(func.second);
  }  
}

void JLCLLVMGenerator::addFuncDeclearation(Frame &frame){
  // see the tutorial about llvm: 
  std::string func_name = frame.name;
  auto llvm_return_type = convertType(frame.returnType);
  std::vector<llvm::Type*> llvm_args;
  for (auto & arg : frame.args)
  {
    llvm_args.push_back(convertType(arg.second));
  }
  llvm::FunctionType* func_type = 
    llvm::FunctionType::get(llvm_return_type, llvm_args, false);
  auto func_dec = llvm::Function::Create(
      func_type, 
      llvm::Function::ExternalLinkage, 
      func_name, 
      LLVM_module_.get());
  
  std::string ss;
  llvm::raw_string_ostream ss2(ss);
  func_dec->print(ss2);
  DEBUG_PRINT("Add function declearation: " + ss);
}


void JLCLLVMGenerator::visitProg(Prog *t) {} //abstract class
void JLCLLVMGenerator::visitTopDef(TopDef *t) {} //abstract class
void JLCLLVMGenerator::visitArg(Arg *t) {} //abstract class
void JLCLLVMGenerator::visitBlk(Blk *t) {} //abstract class
void JLCLLVMGenerator::visitStmt(Stmt *t) {} //abstract class
void JLCLLVMGenerator::visitItem(Item *t) {} //abstract class
void JLCLLVMGenerator::visitType(Type *t) {} //abstract class
void JLCLLVMGenerator::visitExpr(Expr *t) {} //abstract class
void JLCLLVMGenerator::visitAddOp(AddOp *t) {} //abstract class
void JLCLLVMGenerator::visitMulOp(MulOp *t) {} //abstract class
void JLCLLVMGenerator::visitRelOp(RelOp *t) {} //abstract class

void JLCLLVMGenerator::visitProgram(Program *program)
{
  /* Code For Program Goes Here */
  /* iterate through the top definitions */
  // this part is same as the type checker, will add all the functions to the context
  for (ListTopDef::iterator top_def = program->listtopdef_->begin() ; top_def != program->listtopdef_->end() ; ++top_def)
  {
    FnDef* fn_def = reinterpret_cast<FnDef*>(*top_def);
    visitIdent(fn_def->ident_);
    // add the function to the global context
    globalContext.addFrame(fn_def->ident_);
    globalContext.currentFrameName = fn_def->ident_;

    // update the function return type
    Frame& func = globalContext.getFrame(fn_def->ident_);
    fn_def->type_->accept(this);
    func.returnType = temp_type;

    // check function arguments
    if (fn_def->listarg_) fn_def->listarg_->accept(this);
  }
  
  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void JLCLLVMGenerator::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */

  // add a new fucntion definition to the llvm module
  auto & frame = globalContext.getFrame(fn_def->ident_);
  std::string func_name = frame.name;
  auto llvm_return_type = convertType(frame.returnType);
  std::vector<llvm::Type*> llvm_args;
  for (auto & arg : frame.args)
  {
    llvm_args.push_back(convertType(arg.second));
  }
  llvm::FunctionType* func_type = 
    llvm::FunctionType::get(llvm_return_type, llvm_args, false);
  current_func_ = llvm::Function::Create(
      func_type, 
      llvm::Function::ExternalLinkage, 
      func_name, 
      LLVM_module_.get());
  
  
  // reset inner variables before visiting the function body
  block_id = 0;

  // debug print
  std::string ss;
  llvm::raw_string_ostream ss2(ss);
  current_func_->print(ss2);
  DEBUG_PRINT("Add function define: " + ss);

  // cotinue to iterate the function body
  if (fn_def->blk_) fn_def->blk_->accept(this);
}

void JLCLLVMGenerator::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */
  // this part is same as the type checker,
  // will add all the arguments to the function
  // but does not check the types of the arguments in generator
    if (argument->type_) argument->type_->accept(this);
    DEBUG_PRINT("\tArgument name: " + argument->ident_ + 
      "\tArgument type: " + to_string(temp_type));
    Frame& func = globalContext.getFrame(globalContext.currentFrameName);
    // add the argument to the function
    func.addArg(argument->ident_, temp_type);
}

void JLCLLVMGenerator::visitBlock(Block *block)
{
  /* Code For Block Goes Here */
  DEBUG_PRINT( "[" + GeneratorName  +"]" + " visiting Block");
  // create a new block 
  // auto & frame = globalContext.currentFrame();
  // frame.newBlock();
  
  // add the function body
  llvm::BasicBlock* entry = 
    llvm::BasicBlock::Create(*LLVM_Context_, getBlockName(), current_func_);
  LLVM_builder_->SetInsertPoint(entry);
  block_id++;

  if (block->liststmt_) block->liststmt_->accept(this);
  // release the block
  // frame.releaseBlock();
}

void JLCLLVMGenerator::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void JLCLLVMGenerator::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}

void JLCLLVMGenerator::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  
  if (decl->listitem_) decl->listitem_->accept(this);

}

void JLCLLVMGenerator::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);

}

void JLCLLVMGenerator::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  visitIdent(incr->ident_);

}

void JLCLLVMGenerator::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  visitIdent(decr->ident_);

}

void JLCLLVMGenerator::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void JLCLLVMGenerator::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void JLCLLVMGenerator::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void JLCLLVMGenerator::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void JLCLLVMGenerator::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void JLCLLVMGenerator::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void JLCLLVMGenerator::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void JLCLLVMGenerator::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void JLCLLVMGenerator::visitInt(Int *int_)
{
  /* Code For Int Goes Here */
  temp_type = INT;

}

void JLCLLVMGenerator::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */
  temp_type = DOUB;
}

void JLCLLVMGenerator::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */
  temp_type = BOOL;
}

void JLCLLVMGenerator::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */
  temp_type = VOID;
}

void JLCLLVMGenerator::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void JLCLLVMGenerator::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */
  auto & frame = globalContext.currentFrame();
  temp_type = frame.getVarType(e_var->ident_);
  visitIdent(e_var->ident_);

}

void JLCLLVMGenerator::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);
  temp_type = INT;
}

void JLCLLVMGenerator::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);
  temp_type = DOUB;
}

void JLCLLVMGenerator::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */

  temp_type = BOOL;
}

void JLCLLVMGenerator::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */
  temp_type = BOOL;
}

void JLCLLVMGenerator::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void JLCLLVMGenerator::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void JLCLLVMGenerator::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void JLCLLVMGenerator::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void JLCLLVMGenerator::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void JLCLLVMGenerator::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void JLCLLVMGenerator::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void JLCLLVMGenerator::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void JLCLLVMGenerator::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void JLCLLVMGenerator::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void JLCLLVMGenerator::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void JLCLLVMGenerator::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void JLCLLVMGenerator::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void JLCLLVMGenerator::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void JLCLLVMGenerator::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void JLCLLVMGenerator::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void JLCLLVMGenerator::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void JLCLLVMGenerator::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void JLCLLVMGenerator::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void JLCLLVMGenerator::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void JLCLLVMGenerator::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCLLVMGenerator::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCLLVMGenerator::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCLLVMGenerator::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCLLVMGenerator::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void JLCLLVMGenerator::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void JLCLLVMGenerator::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void JLCLLVMGenerator::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void JLCLLVMGenerator::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void JLCLLVMGenerator::visitString(String x)
{
  /* Code for String Goes Here */
}

void JLCLLVMGenerator::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



