/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern VariableCommonChecker. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "JLCChecker.H"
#include "context.H"
#include "util.h"

#include <iostream>
#include <string>
#include <cstdlib>

static type_enum temp_type;

static const std::string checkerName = "VariableCommonChecker";

void VariableCommonChecker::visitProg(Prog *t) {} //abstract class
void VariableCommonChecker::visitTopDef(TopDef *t) {} //abstract class
void VariableCommonChecker::visitArg(Arg *t) {} //abstract class
void VariableCommonChecker::visitBlk(Blk *t) {} //abstract class
void VariableCommonChecker::visitStmt(Stmt *t) {} //abstract class
void VariableCommonChecker::visitItem(Item *t) {} //abstract class
void VariableCommonChecker::visitType(Type *t) {} //abstract class
void VariableCommonChecker::visitExpr(Expr *t) {} //abstract class
void VariableCommonChecker::visitAddOp(AddOp *t) {} //abstract class
void VariableCommonChecker::visitMulOp(MulOp *t) {} //abstract class
void VariableCommonChecker::visitRelOp(RelOp *t) {} //abstract class

void VariableCommonChecker::visitProgram(Program *program)
{
  /* Code For Program Goes Here */
  DEBUG_PRINT( "[" + checkerName +"]" + " visiting Program");
  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void VariableCommonChecker::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */
  
  if (fn_def->type_) fn_def->type_->accept(this);
  visitIdent(fn_def->ident_);

  // update the current frame name, which mean we are in this function
  globalContext.currentFrameName = fn_def->ident_;
  
  if (fn_def->listarg_) fn_def->listarg_->accept(this);
  if (fn_def->blk_) fn_def->blk_->accept(this);
}

void VariableCommonChecker::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */
  if (argument->type_) argument->type_->accept(this);
  visitIdent(argument->ident_);
}

void VariableCommonChecker::visitBlock(Block *block)
{
  /* Code For Block Goes Here */

  if (block->liststmt_) block->liststmt_->accept(this);

}

void VariableCommonChecker::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void VariableCommonChecker::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}

void VariableCommonChecker::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void VariableCommonChecker::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);

}

void VariableCommonChecker::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  visitIdent(incr->ident_);

}

void VariableCommonChecker::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  visitIdent(decr->ident_);

}

void VariableCommonChecker::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void VariableCommonChecker::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void VariableCommonChecker::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void VariableCommonChecker::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void VariableCommonChecker::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void VariableCommonChecker::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void VariableCommonChecker::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void VariableCommonChecker::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void VariableCommonChecker::visitInt(Int *int_)
{
  /* Code For Int Goes Here */
  temp_type = INT;
}

void VariableCommonChecker::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */
  temp_type = DOUB;
}

void VariableCommonChecker::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */
  temp_type = BOOL;

}

void VariableCommonChecker::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */
  temp_type = VOID;

}

void VariableCommonChecker::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void VariableCommonChecker::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void VariableCommonChecker::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void VariableCommonChecker::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);

}

void VariableCommonChecker::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void VariableCommonChecker::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void VariableCommonChecker::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void VariableCommonChecker::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void VariableCommonChecker::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void VariableCommonChecker::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void VariableCommonChecker::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void VariableCommonChecker::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void VariableCommonChecker::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void VariableCommonChecker::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void VariableCommonChecker::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void VariableCommonChecker::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void VariableCommonChecker::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void VariableCommonChecker::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void VariableCommonChecker::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void VariableCommonChecker::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void VariableCommonChecker::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void VariableCommonChecker::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void VariableCommonChecker::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void VariableCommonChecker::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void VariableCommonChecker::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void VariableCommonChecker::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void VariableCommonChecker::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void VariableCommonChecker::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void VariableCommonChecker::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void VariableCommonChecker::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void VariableCommonChecker::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void VariableCommonChecker::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void VariableCommonChecker::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void VariableCommonChecker::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void VariableCommonChecker::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void VariableCommonChecker::visitString(String x)
{
  /* Code for String Goes Here */
}

void VariableCommonChecker::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



