/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printProg(Prog p)
{
  _n_ = 0;
  bufReset();
  ppProg(p, 0);
  return buf_;
}
char *showProg(Prog p)
{
  _n_ = 0;
  bufReset();
  shProg(p);
  return buf_;
}
void ppProg(Prog p, int _i_)
{
  switch(p->kind)
  {
  case is_Program:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListTopDef(p->u.program_.listtopdef_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Prog!\n");
    exit(1);
  }
}

void ppTopDef(TopDef p, int _i_)
{
  switch(p->kind)
  {
  case is_FnDef:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.fndef_.type_, 0);
    ppIdent(p->u.fndef_.ident_, 0);
    renderC('(');
    ppListArg(p->u.fndef_.listarg_, 0);
    renderC(')');
    ppBlk(p->u.fndef_.blk_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing TopDef!\n");
    exit(1);
  }
}

void ppListTopDef(ListTopDef listtopdef, int i)
{
  if (listtopdef == 0)
  { /* nil */
  }
  else if (listtopdef->listtopdef_ == 0)
  { /* last */
    ppTopDef(listtopdef->topdef_, 0);
  }
  else
  { /* cons */
    ppTopDef(listtopdef->topdef_, 0);
    ppListTopDef(listtopdef->listtopdef_, 0);
  }
}

void ppArg(Arg p, int _i_)
{
  switch(p->kind)
  {
  case is_Argument:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.argument_.type_, 0);
    ppIdent(p->u.argument_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Arg!\n");
    exit(1);
  }
}

void ppListArg(ListArg listarg, int i)
{
  if (listarg == 0)
  { /* nil */
  }
  else if (listarg->listarg_ == 0)
  { /* last */
    ppArg(listarg->arg_, 0);
  }
  else
  { /* cons */
    ppArg(listarg->arg_, 0);
    renderC(',');
    ppListArg(listarg->listarg_, 0);
  }
}

void ppBlk(Blk p, int _i_)
{
  switch(p->kind)
  {
  case is_Block:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppListStmt(p->u.block_.liststmt_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Blk!\n");
    exit(1);
  }
}

void ppListStmt(ListStmt liststmt, int i)
{
  if (liststmt == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppStmt(liststmt->stmt_, 0); ppListStmt(liststmt->liststmt_, 0);
  }
}

void ppStmt(Stmt p, int _i_)
{
  switch(p->kind)
  {
  case is_Empty:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBlk(p->u.bstmt_.blk_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Decl:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.decl_.type_, 0);
    ppListItem(p->u.decl_.listitem_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Ass:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.ass_.ident_, 0);
    renderC('=');
    ppExpr(p->u.ass_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Incr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.incr_.ident_, 0);
    renderS("++");
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Decr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.decr_.ident_, 0);
    renderS("--");
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Ret:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("return");
    ppExpr(p->u.ret_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VRet:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("return");
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Cond:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    renderC('(');
    ppExpr(p->u.cond_.expr_, 0);
    renderC(')');
    ppStmt(p->u.cond_.stmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CondElse:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    renderC('(');
    ppExpr(p->u.condelse_.expr_, 0);
    renderC(')');
    ppStmt(p->u.condelse_.stmt_1, 0);
    renderS("else");
    ppStmt(p->u.condelse_.stmt_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_While:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("while");
    renderC('(');
    ppExpr(p->u.while_.expr_, 0);
    renderC(')');
    ppStmt(p->u.while_.stmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SExp:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.sexp_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stmt!\n");
    exit(1);
  }
}

void ppItem(Item p, int _i_)
{
  switch(p->kind)
  {
  case is_NoInit:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.noinit_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Init:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.init_.ident_, 0);
    renderC('=');
    ppExpr(p->u.init_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Item!\n");
    exit(1);
  }
}

void ppListItem(ListItem listitem, int i)
{
  if (listitem == 0)
  { /* nil */
  }
  else if (listitem->listitem_ == 0)
  { /* last */
    ppItem(listitem->item_, 0);
  }
  else
  { /* cons */
    ppItem(listitem->item_, 0);
    renderC(',');
    ppListItem(listitem->listitem_, 0);
  }
}

void ppType(Type p, int _i_)
{
  switch(p->kind)
  {
  case is_Int:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("int");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Doub:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("double");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Bool:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("boolean");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Void:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("void");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Fun:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.fun_.type_, 0);
    renderC('(');
    ppListType(p->u.fun_.listtype_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void ppListType(ListType listtype, int i)
{
  if (listtype == 0)
  { /* nil */
  }
  else if (listtype->listtype_ == 0)
  { /* last */
    ppType(listtype->type_, 0);
  }
  else
  { /* cons */
    ppType(listtype->type_, 0);
    renderC(',');
    ppListType(listtype->listtype_, 0);
  }
}

void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_EVar:
    if (_i_ > 6) renderC(_L_PAREN);
    ppIdent(p->u.evar_.ident_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ELitInt:
    if (_i_ > 6) renderC(_L_PAREN);
    ppInteger(p->u.elitint_.integer_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ELitDoub:
    if (_i_ > 6) renderC(_L_PAREN);
    ppDouble(p->u.elitdoub_.double_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ELitTrue:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ELitFalse:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_EApp:
    if (_i_ > 6) renderC(_L_PAREN);
    ppIdent(p->u.eapp_.ident_, 0);
    renderC('(');
    ppListExpr(p->u.eapp_.listexpr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_EString:
    if (_i_ > 6) renderC(_L_PAREN);
    ppString(p->u.estring_.string_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Neg:
    if (_i_ > 5) renderC(_L_PAREN);
    renderC('-');
    ppExpr(p->u.neg_.expr_, 6);
    if (_i_ > 5) renderC(_R_PAREN);
    break;

  case is_Not:
    if (_i_ > 5) renderC(_L_PAREN);
    renderC('!');
    ppExpr(p->u.not_.expr_, 6);
    if (_i_ > 5) renderC(_R_PAREN);
    break;

  case is_EMul:
    if (_i_ > 4) renderC(_L_PAREN);
    ppExpr(p->u.emul_.expr_1, 4);
    ppMulOp(p->u.emul_.mulop_, 0);
    ppExpr(p->u.emul_.expr_2, 5);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  case is_EAdd:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.eadd_.expr_1, 3);
    ppAddOp(p->u.eadd_.addop_, 0);
    ppExpr(p->u.eadd_.expr_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_ERel:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.erel_.expr_1, 2);
    ppRelOp(p->u.erel_.relop_, 0);
    ppExpr(p->u.erel_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_EAnd:
    if (_i_ > 1) renderC(_L_PAREN);
    ppExpr(p->u.eand_.expr_1, 2);
    renderS("&&");
    ppExpr(p->u.eand_.expr_2, 1);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_EOr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.eor_.expr_1, 1);
    renderS("||");
    ppExpr(p->u.eor_.expr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppListExpr(ListExpr listexpr, int i)
{
  if (listexpr == 0)
  { /* nil */
  }
  else if (listexpr->listexpr_ == 0)
  { /* last */
    ppExpr(listexpr->expr_, 0);
  }
  else
  { /* cons */
    ppExpr(listexpr->expr_, 0);
    renderC(',');
    ppListExpr(listexpr->listexpr_, 0);
  }
}

void ppAddOp(AddOp p, int _i_)
{
  switch(p->kind)
  {
  case is_Plus:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('+');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Minus:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('-');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AddOp!\n");
    exit(1);
  }
}

void ppMulOp(MulOp p, int _i_)
{
  switch(p->kind)
  {
  case is_Times:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('*');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Div:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('/');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Mod:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('%');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing MulOp!\n");
    exit(1);
  }
}

void ppRelOp(RelOp p, int _i_)
{
  switch(p->kind)
  {
  case is_LTH:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_LE:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_GTH:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_GE:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EQU:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("==");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_NE:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("!=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RelOp!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  renderS(tmp);
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shProg(Prog p)
{
  switch(p->kind)
  {
  case is_Program:
    bufAppendC('(');

    bufAppendS("Program");

    bufAppendC(' ');

    shListTopDef(p->u.program_.listtopdef_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Prog!\n");
    exit(1);
  }
}

void shTopDef(TopDef p)
{
  switch(p->kind)
  {
  case is_FnDef:
    bufAppendC('(');

    bufAppendS("FnDef");

    bufAppendC(' ');

    shType(p->u.fndef_.type_);
  bufAppendC(' ');
    shIdent(p->u.fndef_.ident_);
  bufAppendC(' ');
    shListArg(p->u.fndef_.listarg_);
  bufAppendC(' ');
    shBlk(p->u.fndef_.blk_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing TopDef!\n");
    exit(1);
  }
}

void shListTopDef(ListTopDef listtopdef)
{
  bufAppendC('[');
  while(listtopdef != 0)
  {
    if (listtopdef->listtopdef_)
    {
      shTopDef(listtopdef->topdef_);
      bufAppendS(", ");
      listtopdef = listtopdef->listtopdef_;
    }
    else
    {
      shTopDef(listtopdef->topdef_);
      listtopdef = 0;
    }
  }
  bufAppendC(']');
}

void shArg(Arg p)
{
  switch(p->kind)
  {
  case is_Argument:
    bufAppendC('(');

    bufAppendS("Argument");

    bufAppendC(' ');

    shType(p->u.argument_.type_);
  bufAppendC(' ');
    shIdent(p->u.argument_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Arg!\n");
    exit(1);
  }
}

void shListArg(ListArg listarg)
{
  bufAppendC('[');
  while(listarg != 0)
  {
    if (listarg->listarg_)
    {
      shArg(listarg->arg_);
      bufAppendS(", ");
      listarg = listarg->listarg_;
    }
    else
    {
      shArg(listarg->arg_);
      listarg = 0;
    }
  }
  bufAppendC(']');
}

void shBlk(Blk p)
{
  switch(p->kind)
  {
  case is_Block:
    bufAppendC('(');

    bufAppendS("Block");

    bufAppendC(' ');

    shListStmt(p->u.block_.liststmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Blk!\n");
    exit(1);
  }
}

void shListStmt(ListStmt liststmt)
{
  bufAppendC('[');
  while(liststmt != 0)
  {
    if (liststmt->liststmt_)
    {
      shStmt(liststmt->stmt_);
      bufAppendS(", ");
      liststmt = liststmt->liststmt_;
    }
    else
    {
      shStmt(liststmt->stmt_);
      liststmt = 0;
    }
  }
  bufAppendC(']');
}

void shStmt(Stmt p)
{
  switch(p->kind)
  {
  case is_Empty:

    bufAppendS("Empty");




    break;
  case is_BStmt:
    bufAppendC('(');

    bufAppendS("BStmt");

    bufAppendC(' ');

    shBlk(p->u.bstmt_.blk_);

    bufAppendC(')');

    break;
  case is_Decl:
    bufAppendC('(');

    bufAppendS("Decl");

    bufAppendC(' ');

    shType(p->u.decl_.type_);
  bufAppendC(' ');
    shListItem(p->u.decl_.listitem_);

    bufAppendC(')');

    break;
  case is_Ass:
    bufAppendC('(');

    bufAppendS("Ass");

    bufAppendC(' ');

    shIdent(p->u.ass_.ident_);
  bufAppendC(' ');
    shExpr(p->u.ass_.expr_);

    bufAppendC(')');

    break;
  case is_Incr:
    bufAppendC('(');

    bufAppendS("Incr");

    bufAppendC(' ');

    shIdent(p->u.incr_.ident_);

    bufAppendC(')');

    break;
  case is_Decr:
    bufAppendC('(');

    bufAppendS("Decr");

    bufAppendC(' ');

    shIdent(p->u.decr_.ident_);

    bufAppendC(')');

    break;
  case is_Ret:
    bufAppendC('(');

    bufAppendS("Ret");

    bufAppendC(' ');

    shExpr(p->u.ret_.expr_);

    bufAppendC(')');

    break;
  case is_VRet:

    bufAppendS("VRet");




    break;
  case is_Cond:
    bufAppendC('(');

    bufAppendS("Cond");

    bufAppendC(' ');

    shExpr(p->u.cond_.expr_);
  bufAppendC(' ');
    shStmt(p->u.cond_.stmt_);

    bufAppendC(')');

    break;
  case is_CondElse:
    bufAppendC('(');

    bufAppendS("CondElse");

    bufAppendC(' ');

    shExpr(p->u.condelse_.expr_);
  bufAppendC(' ');
    shStmt(p->u.condelse_.stmt_1);
  bufAppendC(' ');
    shStmt(p->u.condelse_.stmt_2);

    bufAppendC(')');

    break;
  case is_While:
    bufAppendC('(');

    bufAppendS("While");

    bufAppendC(' ');

    shExpr(p->u.while_.expr_);
  bufAppendC(' ');
    shStmt(p->u.while_.stmt_);

    bufAppendC(')');

    break;
  case is_SExp:
    bufAppendC('(');

    bufAppendS("SExp");

    bufAppendC(' ');

    shExpr(p->u.sexp_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Stmt!\n");
    exit(1);
  }
}

void shItem(Item p)
{
  switch(p->kind)
  {
  case is_NoInit:
    bufAppendC('(');

    bufAppendS("NoInit");

    bufAppendC(' ');

    shIdent(p->u.noinit_.ident_);

    bufAppendC(')');

    break;
  case is_Init:
    bufAppendC('(');

    bufAppendS("Init");

    bufAppendC(' ');

    shIdent(p->u.init_.ident_);
  bufAppendC(' ');
    shExpr(p->u.init_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Item!\n");
    exit(1);
  }
}

void shListItem(ListItem listitem)
{
  bufAppendC('[');
  while(listitem != 0)
  {
    if (listitem->listitem_)
    {
      shItem(listitem->item_);
      bufAppendS(", ");
      listitem = listitem->listitem_;
    }
    else
    {
      shItem(listitem->item_);
      listitem = 0;
    }
  }
  bufAppendC(']');
}

void shType(Type p)
{
  switch(p->kind)
  {
  case is_Int:

    bufAppendS("Int");




    break;
  case is_Doub:

    bufAppendS("Doub");




    break;
  case is_Bool:

    bufAppendS("Bool");




    break;
  case is_Void:

    bufAppendS("Void");




    break;
  case is_Fun:
    bufAppendC('(');

    bufAppendS("Fun");

    bufAppendC(' ');

    shType(p->u.fun_.type_);
  bufAppendC(' ');
    shListType(p->u.fun_.listtype_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Type!\n");
    exit(1);
  }
}

void shListType(ListType listtype)
{
  bufAppendC('[');
  while(listtype != 0)
  {
    if (listtype->listtype_)
    {
      shType(listtype->type_);
      bufAppendS(", ");
      listtype = listtype->listtype_;
    }
    else
    {
      shType(listtype->type_);
      listtype = 0;
    }
  }
  bufAppendC(']');
}

void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    bufAppendC('(');

    bufAppendS("EVar");

    bufAppendC(' ');

    shIdent(p->u.evar_.ident_);

    bufAppendC(')');

    break;
  case is_ELitInt:
    bufAppendC('(');

    bufAppendS("ELitInt");

    bufAppendC(' ');

    shInteger(p->u.elitint_.integer_);

    bufAppendC(')');

    break;
  case is_ELitDoub:
    bufAppendC('(');

    bufAppendS("ELitDoub");

    bufAppendC(' ');

    shDouble(p->u.elitdoub_.double_);

    bufAppendC(')');

    break;
  case is_ELitTrue:

    bufAppendS("ELitTrue");




    break;
  case is_ELitFalse:

    bufAppendS("ELitFalse");




    break;
  case is_EApp:
    bufAppendC('(');

    bufAppendS("EApp");

    bufAppendC(' ');

    shIdent(p->u.eapp_.ident_);
  bufAppendC(' ');
    shListExpr(p->u.eapp_.listexpr_);

    bufAppendC(')');

    break;
  case is_EString:
    bufAppendC('(');

    bufAppendS("EString");

    bufAppendC(' ');

    shString(p->u.estring_.string_);

    bufAppendC(')');

    break;
  case is_Neg:
    bufAppendC('(');

    bufAppendS("Neg");

    bufAppendC(' ');

    shExpr(p->u.neg_.expr_);

    bufAppendC(')');

    break;
  case is_Not:
    bufAppendC('(');

    bufAppendS("Not");

    bufAppendC(' ');

    shExpr(p->u.not_.expr_);

    bufAppendC(')');

    break;
  case is_EMul:
    bufAppendC('(');

    bufAppendS("EMul");

    bufAppendC(' ');

    shExpr(p->u.emul_.expr_1);
  bufAppendC(' ');
    shMulOp(p->u.emul_.mulop_);
  bufAppendC(' ');
    shExpr(p->u.emul_.expr_2);

    bufAppendC(')');

    break;
  case is_EAdd:
    bufAppendC('(');

    bufAppendS("EAdd");

    bufAppendC(' ');

    shExpr(p->u.eadd_.expr_1);
  bufAppendC(' ');
    shAddOp(p->u.eadd_.addop_);
  bufAppendC(' ');
    shExpr(p->u.eadd_.expr_2);

    bufAppendC(')');

    break;
  case is_ERel:
    bufAppendC('(');

    bufAppendS("ERel");

    bufAppendC(' ');

    shExpr(p->u.erel_.expr_1);
  bufAppendC(' ');
    shRelOp(p->u.erel_.relop_);
  bufAppendC(' ');
    shExpr(p->u.erel_.expr_2);

    bufAppendC(')');

    break;
  case is_EAnd:
    bufAppendC('(');

    bufAppendS("EAnd");

    bufAppendC(' ');

    shExpr(p->u.eand_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.eand_.expr_2);

    bufAppendC(')');

    break;
  case is_EOr:
    bufAppendC('(');

    bufAppendS("EOr");

    bufAppendC(' ');

    shExpr(p->u.eor_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.eor_.expr_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shListExpr(ListExpr listexpr)
{
  bufAppendC('[');
  while(listexpr != 0)
  {
    if (listexpr->listexpr_)
    {
      shExpr(listexpr->expr_);
      bufAppendS(", ");
      listexpr = listexpr->listexpr_;
    }
    else
    {
      shExpr(listexpr->expr_);
      listexpr = 0;
    }
  }
  bufAppendC(']');
}

void shAddOp(AddOp p)
{
  switch(p->kind)
  {
  case is_Plus:

    bufAppendS("Plus");




    break;
  case is_Minus:

    bufAppendS("Minus");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing AddOp!\n");
    exit(1);
  }
}

void shMulOp(MulOp p)
{
  switch(p->kind)
  {
  case is_Times:

    bufAppendS("Times");




    break;
  case is_Div:

    bufAppendS("Div");




    break;
  case is_Mod:

    bufAppendS("Mod");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing MulOp!\n");
    exit(1);
  }
}

void shRelOp(RelOp p)
{
  switch(p->kind)
  {
  case is_LTH:

    bufAppendS("LTH");




    break;
  case is_LE:

    bufAppendS("LE");




    break;
  case is_GTH:

    bufAppendS("GTH");




    break;
  case is_GE:

    bufAppendS("GE");




    break;
  case is_EQU:

    bufAppendS("EQU");




    break;
  case is_NE:

    bufAppendS("NE");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RelOp!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufAppendC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

