
g++  Fuck.C -fPIC -shared -o Fuck.so \
	-I/nfs4/sol.ita.chalmers.se/ufs/groups/manual20/sup_de/sup64/llvm-16.0.5 -I/nfs4/sol.ita.chalmers.se/ufs/groups/manual20/sup_de/sup64/llvm-16.0.5 \
	`llvm-config --cxxflags --ldflags --libs --system-libs`