/* File generated by the BNF Converter (bnfc 2.9.4). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitProg(Prog p);
void visitTopDef(TopDef p);
void visitListTopDef(ListTopDef p);
void visitArg(Arg p);
void visitListArg(ListArg p);
void visitBlk(Blk p);
void visitListStmt(ListStmt p);
void visitStmt(Stmt p);
void visitItem(Item p);
void visitListItem(ListItem p);
void visitType(Type p);
void visitListType(ListType p);
void visitExpr(Expr p);
void visitListExpr(ListExpr p);
void visitAddOp(AddOp p);
void visitMulOp(MulOp p);
void visitRelOp(RelOp p);


void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

